server:
  port: 8081

spring:
  application:
    name: redis-string-pv
#redis
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
#log
logging:
  level:
    cn:
      ityoudream: debug
