spring:
  application:
    name: redis-string-id
  swagger2:
    enabled: true
# redis
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
server:
  port: 8081

#log
logging:
  level:
    cn:
      ityoudream: debug
